### ISSUE TITLE
css snippets

### ISSUE THREAD

**Issue by fi3ework** [fi3ework/blog#12]
- 解决 `transition` 对 `display` 无效，
  - 使用 `visibility: visible` 和 `visibility: hidden` 代替 `display: block` 和 `display: none`

    ```html
    <div class="wrapper">
      <h3>title</h3>
      <p>Item</p>
    </div>
    ```

    ```css
    .wrapper{
      position: relative;
    }

    .wrapper p {
      position: absolute;
      transition: all 0.3s ease-in 0s;
      visibility: hidden;
      opacity: 0;
    }

    .wrapper:hover p {
      visibility: visible;
      opacity: 1;
    }
    ```

  - 不使用 `transition`，而是使用 `animation`

    ```html
    <div class="wrapper">
      <h3>title</h3>
      <p>Item</p>
    </div>
    ```

    ```css
    @keyframes fadeIn {
        from { opacity: 0; }
          to { opacity: 1; }
    }

    .wrapper p {
      position: relative;
      display: none;
    }

    .wrapper:hover p {
      position: absolute;
      display: block;
      animation: fadeIn 1s;
    }
    ```
